#include "SyntacticAnalyzer.h"

void SyntacticAnalyzer::programa(){ }
void SyntacticAnalyzer::declaracoes_variaveis(){ }
void SyntacticAnalyzer::lista_declaracoes_variaveis(){ }
void SyntacticAnalyzer::lista_declaracoes_variaveis_auxiliar(){ }
void SyntacticAnalyzer::lista_de_identificadores(){ }
void SyntacticAnalyzer::lista_de_identificadores_auxiliar(){ }
void SyntacticAnalyzer::tipo(){ }
void SyntacticAnalyzer::declaracoes_de_subprogramas(){ }
void SyntacticAnalyzer::declaracoes_de_subprogramas_auxiliar(){ }
void SyntacticAnalyzer::declaracao_de_subprograma(){ }
void SyntacticAnalyzer::argumentos(){ }
void SyntacticAnalyzer::lista_de_parametros(){ }
void SyntacticAnalyzer::lista_de_parametros_auxiliar(){ }
void SyntacticAnalyzer::comando_composto(){ }
void SyntacticAnalyzer::comandos_opcionais(){ }
void SyntacticAnalyzer::lista_de_comandos(){ }
void SyntacticAnalyzer::lista_de_comandos_auxiliar(){ }
void SyntacticAnalyzer::comando(){ }
void SyntacticAnalyzer::parte_else(){ }
void SyntacticAnalyzer::variavel(){ }
void SyntacticAnalyzer::ativacao_de_procedimentos(){ }
void SyntacticAnalyzer::lista_de_expressoes(){ }
void SyntacticAnalyzer::lista_de_expressoes_auxiliar(){ }
void SyntacticAnalyzer::expressao(){ }
void SyntacticAnalyzer::expressao_simples(){ }
void SyntacticAnalyzer::expressao_simples_auxiliar(){ }
void SyntacticAnalyzer::termo(){ }
void SyntacticAnalyzer::termo_auxiliar(){ }
void SyntacticAnalyzer::fator(){ }
void SyntacticAnalyzer::sinal(){ }
void SyntacticAnalyzer::op_relacional(){ }
void SyntacticAnalyzer::op_aditivo(){ }
void SyntacticAnalyzer::op_multiplicativo(){ }